config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  resources :users
  get 'signup', to: 'users#new'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
	validates :body, presence: true

	scope :custom_display, -> { order(:created_at).last(50) }
end

app/models/user.rb
class User < ApplicationRecord
	validates :username, presence: true, length: { minimum: 2, maximum: 25 }
	VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
	uniqueness: { case_sensitive: false },
	length: { maximum: 110 },
	format: { with: VALID_EMAIL }
	has_secure_password
	has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:error] = "Only registered users allowed"
			redirect_to login_path
		end
	end
	
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
	before_action :require_user

	def index
		@message = Message.new
		@messages = Message.custom_display
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_user

	def create
		message = current_user.messages.build(message_params)
		if message.save
			ActionCable.server.broadcast "chatroom_channel", say: message_render(message)
		end
	end

	private

	def message_params
		params.require(:message).permit(:body)
	end

	def message_render(message)
		render(partial: 'message', locals: { message: message })
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :logged_in_redirect, only: [:new, :create]

	def new
	end

	def create
		user = User.find_by(username: params[:session][:username])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "Welcome to MessageMe!"
			redirect_to root_path
		else
			flash.now[:error] = "Incorrect username or password"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have loged out. Bye."
		redirect_to login_path
	end

	private
	
	def logged_in_redirect
		if logged_in?
			flash[:info] = "You are already logged in"
			redirect_to root_path
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user
	before_action :require_user
	before_action :require_same_user

	def new
		@user = User.new
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your information updated successfully"
			redirect_to user_path
		else
			render 'edit'
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the MessageMe chat #{@user.username}!"
			redirect_to root_path
		else
			render 'new'
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil if @user == current_user
		flash[:success] = "User account and all messages sucessfullly deleted. Sorry to see you go :("
		redirect_to login_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if @user != current_user
			flash[:error] = "You can only see your own profile!"
			redirect_to root_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h3 class="ui center aligned icon header">
  <i class="circular bullhorn icon teal"></i>
  Welcome to the <em>MessageMe</em> chatroom
</h3>

<div class="ui two column grid">
	<div class="twelve wide column">
		<div class="ui fluid raise card chatbox">
			<div class="content" id="messages">
				<div class="ui feed" id="message-container">
			  	<%= render @messages %>
				</div>
			</div>
			<div class="extra content">
				<%= form_for(@message, html: { class: "ui reply form", role: "form" }, url: message_path, remote: true) do |f| %>
					<div class="field">
						<div class="ui fluid icon input">
							<%= f.text_field :body %>
							<%= f.button '<i class="icon edit bordered inverted teal"></i>'.html_safe %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="four wide column">
		<div class="ui fluid raised card chatbox">
  		<div class="content">
				<div class="ui inverted vertical menu teal">
				  <a class="teal item">Home</a>
				  <a class="teal item">Messages</a>
				  <a class="item teal">Friends</a>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footerspacer"></div>
<div class="ui inverted teal vertical footer segment">
  <div class="ui container">
      &copy; 2020, Message me
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<div class="ui <%= name %> message transition">
	  <i class="close icon"></i>
	  <div class="header">
	    <%= msg %>
	  </div>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui tiny menu inverted teal">
  <div class="ui container">
    <%= link_to "Chat", root_path, class: "item teal" %>
    <a class="teal item">Messages</a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to "Profile", user_path(id: current_user.id), class: "item" %>
            <%= link_to "Log out", logout_path, class: "item", method: :delete %>
          <% else %>
            <%= link_to "Log in", login_path, class: "item" %>
            <%= link_to "Sign up", signup_path, class: "item teal" %>
          <% end %>
        </div>
      </div>
      <% if !logged_in? %>
        <div class="item">
          <%= link_to "Log in", login_path, class: "ui primary button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navigation' %>

    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
      [<%= message[:created_at].strftime("%H:%M:%S") %>] <%= message.user.username %>: <%= message[:body] %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="column">
  <%= form_with(model: @user, local: true, html: {class: "ui form", role: "form"}) do |f| %>
    <div class="field">
      <%= f.label :username, "Username" %>
      <div class="ui left icon input">
        <%= f.text_field :username, placeholder: "Username" %>
        <i class="user icon"></i>
      </div>
    </div>
    <div class="field">
      <%= f.label :email, "Email" %>
      <div class="ui left icon input">
        <%= f.email_field :email, placeholder: "e-mail address" %>
        <i class="mail icon"></i>
      </div>
    </div>
    <div class="field">
      <%= f.label :password, "Password" %>
      <div class="ui left icon input">
        <%= f.password_field :password, placeholder: "Password" %>
        <i class="lock icon"></i>
      </div>
    </div>
    <%= f.submit(@user.new_record? ? "Signup" : "Update your information", class: "ui teal submit button") %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h3 class="ui center aligned icon header">
	<em>MessageMe</em>
</h3>

<h3 class="ui center aligned icon header">
	<i class="circular bullhorn icon teal inverted relaxed"></i>
</h3>

<h4 class="ui center aligned header">
	<div class="ui teal message">Edit your profile information.</div>
</h4>

<div class="ui placeholder raised segment">
  <div class="ui one column very relaxed stackable grid">
  	<%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<h3 class="ui center aligned icon header">
	Welcome to <em>MessageMe</em></h3>
  <h3 class="ui center aligned icon header"><i class="circular bullhorn icon teal inverted relaxed"></i></h3>
<h4 class="ui center aligned header">
	<div class="ui teal message">Please Sign up to continue. Provide valid e-mail for password reset.
	</div>
</h4>

<div class="ui placeholder raised segment">
  <div class="ui one column very relaxed stackable grid">
  	<%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<h4 class="ui center aligned header">
  User information
</h4>
<table class="ui single line table teal">
  <thead>
    <tr>
      <th>Userame</th>
      <th>Registration Date</th>
      <th>E-mail address</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.username %></td>
      <td><%= @user.created_at.strftime("%F") %></td>
      <td><%= @user.email %></td>
    </tr>
  </tbody>
</table>
<div class="ui center aligned container">
  <div class="ui buttons">
    <%= link_to 'Update information', edit_user_path(@user), class: "ui teal button" %>
      <div class="or"></div>
    <%= link_to 'Delete your profile', user_path(@user), method: :delete, class: "ui grey button", data: { confirm: "This action is irreversible! Are you sure?"} %>
  </div>
</div>